config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  
  get 'people/:id/like/:like_id', to: 'people#show', as: 'user_profile'

  devise_scope :user do
    get 'about', to: 'devise/sessions#about'
    get 'phone', to: 'devise/sessions#phone'
    get 'profile', to: 'devise/sessions#profile'
    get 'presentation', to: 'devise/sessions#presentation'
  end
  
  get 'my-rooms', to: 'pages#my_rooms'

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :rooms do
    resources :likes do
      resources :compatibilities, only: [:create]
    end
  end

  resources :abouts, only: [:new, :create]
  resources :answers, only: [:new, :create, :show, :index, :destroy]
  resources :phones, only: [:new, :create]

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  post 'chatrooms/:user_id', to: 'chatrooms#create', as: 'chatrooms_create'

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def show
    @person = User.find(params[:id])
    @like = Like.find(params[:like_id])
  end
end

app/views/people/show.html.erb
<div class="container mt-3 px-2 mx-2 my-2" , style="width: 95%">

  <div class="profile-container">


    <div class="name-pic d-flex justify-content-center align-items-center pt-3">

    <% if @person.facebook_picture_url %>
    <div class="me-3">
      <%= image_tag @person.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    </div>
    <h1 class="mt-2"><%= @person.first_name %>'s Profile</h1>
    <% elsif @person.avatar.attached? %>
    <div class="me-3">
      <%= cl_image_tag @person.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    </div>
    <h1 class="mt-2"><%= @person.name %>'s Profile</h1>
    <% else %>
    <div class="me-3">
      <%= image_tag "avatar.webp", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
    </div>
    <h1 class="mt-2"><%= @person.name %>'s Profile</h1>
    <% end %>

</div>


  <div class="container mb-4 pb-4 px-4">

    <% if @person.about %>
    <p><%= @person.about.about_user %></p>
    <% end %>

    <div class="match-button">
      <%= link_to room_like_compatibilities_path(@like.room, @like), method: :post, class: "btn main-button py-2 rounded-pill", id: "" do %>
      <span>Like back<i style="color: #fff" class="fas fa-heart  ms-1"></i></span>
      <% end %>
    </div>
  </div>
</div>





      <h4 class="mt-4 py-1" style="border-bottom: 2px solid #ed3b5a; font-size: 18px"><strong>Questionary:</strong></h4>

  <% @person.answers.each_with_index do |answer, index| %>

  <div class="questions" style="border-bottom: 1px solid #ed3b5a">

    <p class="question-description mt-2" style="color: #137e8f; font-weight: 600;">
          <%= answer.question.question_description %></p>

           <p class="answer-description"><%= answer.question.answer_description.partition('10').first %></p>
        <p class="answer-description">10 <%= answer.question.answer_description.partition('10 ').last %></p>

    <div class="choice d-flex justify-content-between" style="font-weight: 600">
      <% if @person.first_name %>
      <small><%= @person.first_name %>'s rating: <%= answer.score %></small>
      <% else %>
      <small><%= @person.name %>'s rating: <%= answer.score %></small>
      <% end %>
      <small>Your rating: <%= current_user.answers[index].score %></small>
    </div>



  </div>
  <% end %>
      <div class="match-button my-4">
      <%= link_to room_like_compatibilities_path(@like.room, @like), method: :post, class: "btn main-button py-2 rounded-pill", id: "" do %>
      <span>Like back<i style="color: #fff" class="fas fa-heart  ms-1"></i></span>
      <% end %>
    </div>