config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  
  get 'people/:id/like/:like_id', to: 'people#show', as: 'user_profile'

  devise_scope :user do
    get 'about', to: 'devise/sessions#about'
    get 'phone', to: 'devise/sessions#phone'
    get 'profile', to: 'devise/sessions#profile'
    get 'presentation', to: 'devise/sessions#presentation'
  end
  
  get 'my-rooms', to: 'pages#my_rooms'

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :rooms do
    resources :likes do
      resources :compatibilities, only: [:create]
    end
  end

  resources :abouts, only: [:new, :create]
  resources :answers, only: [:new, :create, :show, :index, :destroy]
  resources :phones, only: [:new, :create]

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  post 'chatrooms/:user_id', to: 'chatrooms#create', as: 'chatrooms_create'

end

app/views/shared/_form.html.erb
<%= simple_form_for(room) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :roommates,
                label:false,
                placeholder: 'How many people live in the house?',
                input_html: { class: "my-form-style my-3" } %>
    <%= f.input :size,
                label:false,
                placeholder: 'In meters square',
                input_html: { class: "my-form-style my-3" } %>
    <%= f.input :address,
                label:false,
                placeholder: 'Address',
                input_html: { class: "my-form-style my-3" } %>
    <%= f.input :city,
                label:false,
                placeholder: 'City',
                input_html: { class: "my-form-style my-3" } %>
    <%= f.input :start_date, as: :date, html5: true,
                input_html: { class: "my-form-style my-3" } %>
    <%= f.input :end_date, as: :date, html5: true,
                input_html: { class: "my-form-style my-3" } %>
    <%= f.input :pets,
                collection: Room::PETSPER,
                as: :radio_buttons,
                input_html: { style: "margin-left: -0.9em; margin-right: 0.5em" } %><br>
    <%= f.input :smoking,
                collection: Room::SMOKEPER,
                as: :radio_buttons,
                input_html: { style: "margin-left: -0.9em; margin-right: 0.5em" } %><br>
    <%= f.input :visitors,
                collection: Room::VISITPER,
                as: :radio_buttons,
                input_html: { style: "margin-left: -0.9em; margin-right: 0.5em" } %><br>
    <%= f.input :description,
                placeholder: 'Tell the comunity a bit about the co living in the house.',
                input_html: {
                  rows: 5,
                  class: "my-form-style px-4 py-4" } %>
    <%= f.input :floor,
                placeholder: 'Which floor?',
                label:false,
                input_html: { class: "my-form-style my-3" } %>
    <%= f.input :price,
                placeholder: 'Price',
                label:false,
                input_html: { class: "my-form-style my-3" } %>
    <%= f.input :utilities,
                collection: Room::UTILIPER,
                as: :radio_buttons,
                input_html: { style: "margin-left: -0.9em; margin-right: 0.5em" }  %>
    <br>
    <label class="btn btn-secondary my-form-style upload-button">
      Upload pictures
      <span style="display:none;">
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      </span>
    </label>
  </div>
  <div class="form-actions mt-3" style="padding-bottom: 30px">
    <%= f.button :submit, class: 'btn btn-face' %>
  </div>
</div>
<% end  %>

app/views/shared/_info_window.html.erb
<div class="container map-card">

  <div class="">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <% if room.photos.attached? %>
        <% room.photos.each_with_index do |photo, index| %>
        <div class="carousel-item <%= index.zero? ? "active" : "" %>">
          <%= cl_image_tag photo.key, class: "d-block w-100", height: 120, width: 200, crop: :fill %>
        </div>
        <% end %>
        <% else %>
        <div class="carousel-item active">
          <%= image_tag 'no-image-found.png',  height: 120, width: 220, crop: :fill %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

    <div class="map-info">
      <div class="map-info-1">
        <p><strong> <%= room.address %> </strong></p>
        <%= link_to "Show more", room_url(room),  class: "btn-map" %>
      </div>
      <div class="map-info-2">
        <p class="badge rounded-pill bg-secondary map-compatibility"><%= room.compatibility %>% </p>
        <p>R$<%= room.price %></p>
      </div>
    </div>

app/views/shared/_liked_room_card.html.erb
<div>
  <% if current_user.likes && current_user.likes.length > 0 %>

    <% current_user.likes.each do |like| %>
      <div class="card-trip" id="resize-cards-<%= like.room.id %>">
        <div id=<%= "carouselExampleIndicators#{like.room.id}" %> class="carousel slide" data-bs-ride="carousel">

          <div class="carousel-inner">
            <% if like.room.photos.attached? %>
              <% like.room.photos.each_with_index do |photo, index| %>
                <div class="carousel-item <%= index.zero? ? "active" : "" %>">
                  <%= cl_image_tag photo.key, class: "d-block w-100", height: 200, width: 400, crop: :fill %>
                </div>
              <% end %>
            <% else %>
              <div class="carousel-item active">
                <%= image_tag 'no-image-found.png', class: "d-block w-100", height: 200, width: 400, crop: :fill %>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="<%= "#carouselExampleIndicators#{like.room.id}" %>" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="<%= "#carouselExampleIndicators#{like.room.id}" %>" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
      <div class="card-trip-infos">
        <div>
          <h2><%= like.room.address  %></h2>
          <p> <strong> <%= like.room.city %> </strong> </p>
          <p class="mt-2"> <strong> <%= like.room.start_date.strftime('%dth %B') %> </strong> </p>



          <span>
            <%= link_to "Show more", room_url(like.room) %>


          <%= link_to room_like_path(like.room.id, like.room.likes.where(user: current_user).first.id), method: :delete, class: 'card-heart-my-rooms' do %>
            <i class="fas fa-heart liked ms-1"></i>
          <% end %>



          </span>
        </div>
        <div>
          <span class="badge rounded-pill compatibility", style="background-color: #ed3b5a"><%= like.room.compatibility %>%</span>
          <h2 class="card-trip-pricing">R$<%= sprintf("%.2f", like.room.price) %></h2>
          <% if like.room.user.avatar.attached? %>
            <%= cl_image_tag like.room.user.avatar.key, class: "card-trip-user avatar", alt: "avatar" %>
          <% elsif like.room.user.uid %>
            <%= image_tag like.room.user.facebook_picture_url, class: "card-trip-user avatar", alt: "avatar" %>
          <% else %>
            <%= image_tag "avatar.webp", class: "card-trip-user avatar-bordered" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar  navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to rooms_path, class: "navbar-brand" do %>
      <h5>FlatMatch</h5>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
           <%= link_to 'Offer a Room', new_room_path, class: "dropdown-item" %>
            <%= link_to "Edit account", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "My Profile", profile_path, class: "dropdown-item" %>
            <%= link_to "Dashboard", my_rooms_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit account", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "My Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Dashboard", my_rooms_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_previous_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h5>FlatMatch</h5>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <span class="nav-link disabled">
              <%= current_user.first_name %>
            </span>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.facebook_picture_url %>
              <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "avatar.webp", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit account", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_room_cards.html.erb
<% rooms.order("compatibility desc").each do |room| %>
  <% if room.user.id != current_user.id %>
    <div class="card-trip" id="resize-cards-<%= room.id %>">
      <div id=<%= "carouselExampleIndicators#{room.id}" %> class="carousel slide"  data-bs-interval="false">
        <div class="carousel-inner">
          <% if room.photos.attached? %>
            <% room.photos.each_with_index do |photo, index| %>
              <div class="carousel-item <%= index.zero? ? "active" : "" %>">
                <%= cl_image_tag photo.key, class: "d-block w-100", height: 200, width: 400, crop: :fill %>
              </div>
            <% end %>
          <% else %>
            <div class="carousel-item active">
              <%= image_tag 'no-image-found.png', height: 200, width: 400, crop: :fill %>
            </div>
          <% end %>
        </div>

        <button class="carousel-control-prev" type="button" data-bs-target=<%= "#carouselExampleIndicators#{room.id}" %> data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target=<%= "#carouselExampleIndicators#{room.id}" %> data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <div class="card-trip-infos">
        <div>
          <h2><%= room.address  %></h2>
          <p> <strong> <%= room.city %> </strong> </p>
          <p class="mt-2"> <strong> <%= room.start_date.strftime('%dth %B') %> </strong> </p>
          <span>
            <%= link_to "Show more", room_url(room) %>
            <% if room.likes && room.likes.where(user: current_user).length > 0 %>
              <%= link_to room_like_path(room.id, room.likes.where(user: current_user).first.id), method: :delete, class: 'card-heart', remote: true do %>
                <i class="fas fa-heart liked ms-1"></i>
              <% end %>
            <% else %>
              <%= link_to room_likes_path(room.id), method: :post, class: 'card-heart', remote: true do %>
                <i class="fas fa-heart disliked ms-1"></i>
              <% end %>
            <% end %>
          </span>
        </div>
        <div>
          <span class="badge rounded-pill compatibility", style="background-color: #ed3b5a"><%= room.compatibility %>%</span>
          <h2 class="card-trip-pricing">R$<%= sprintf("%.2f", room.price) %></h2>
          <% if room.user.avatar.attached? %>
            <%= cl_image_tag room.user.avatar.key, class: "card-trip-user avatar", alt: "avatar" %>
          <% elsif room.user.uid %>
            <%= image_tag room.user.facebook_picture_url, class: "card-trip-user avatar", alt: "avatar" %>
          <% else %>
            <%= image_tag "avatar.webp", class: "card-trip-user avatar-bordered" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>